version: '3'

# Go-related tasks
# Include this file in your project with:
#   includes:
#     go: ./path/to/golang/Taskfile.yml
# Or use remote include:
#   includes:
#     go:
#       taskfile: https://raw.githubusercontent.com/exhuma/taskfiles/main/golang/Taskfile.yml

tasks:
  build:
    desc: Build Go application
    cmds:
      - go build -o {{.OUTPUT | default "bin/app"}} .

  test:
    desc: Run Go tests
    cmds:
      - go test -v ./...

  test-coverage:
    desc: Run Go tests with coverage
    cmds:
      - go test -v -coverprofile=coverage.out ./...
      - go tool cover -html=coverage.out

  lint:
    desc: Run Go linters
    cmds:
      - golangci-lint run

  fmt:
    desc: Format Go code
    cmds:
      - go fmt ./...

  vet:
    desc: Run go vet
    cmds:
      - go vet ./...

  mod-tidy:
    desc: Tidy Go modules
    cmds:
      - go mod tidy

  clean:
    desc: Clean build artifacts
    cmds:
      - rm -rf bin/
      - go clean
