version: '3'

# Python-related tasks
# Include this file in your project with:
#   includes:
#     py: ./path/to/python/Taskfile.yml
# Or use remote include:
#   includes:
#     py:
#       taskfile: https://raw.githubusercontent.com/exhuma/taskfiles/main/python/Taskfile.yml

tasks:

  clean:
    desc: Clean Python artifacts
    cmds:
      - find . -type d -name __pycache__ -exec rm -rf {} +
      - find . -type f -name "*.pyc" -delete
      - find . -type d -name "*.egg-info" -exec rm -rf {} +
      - rm -rf .pytest_cache
      - rm -rf dist build
